server:
  port: 8184
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ${DB_PASSWORD:root}
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/sapientdb}
    username: ${DB_USER:root}
  application:
    name: dept-service
    
  jpa:
    show-sql: true
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${UREKA_SERVER_URL:http://localhost:8761/eureka/}